# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b2d2b2dd742fc9b6ec3a57d0df32d6d807c4ff6b1624d200bb11aea36b6982bf6bbe2c7339f903322d2928b89fa20f8272cb27ec73a4d5d6e17f806a4788745

test:
  secret_key_base: 03a42996030d2cb3c17beb6d6d1fe3624f43c0e6875c6a0804cb5e0cc6c28f97bfea936547c11bf974c0137bf21fab4a02e2fb78a5c8cae5f712cbcf25ae5045

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
